In [1]:
import numpy as np

In [2]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

## e do potęgi w array

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A = np.random.randn(10)
A

array([-1.29448206, -0.17535568, -1.04661303,  0.16442299,  1.65181276,
       -0.12096732, -0.34211168,  1.46179422,  1.38764981,  0.74787963])

In [8]:
B = np.random.randn(10)
B

array([-0.58027795,  0.05304831,  1.61503833,  0.23649667,  0.34761582,
       -0.02631042,  1.52283485,  0.35502166, -0.53299562,  0.34550567])

In [9]:
# Binary functions
np.add(A,B)

array([-1.87476001, -0.12230737,  0.5684253 ,  0.40091966,  1.99942858,
       -0.14727774,  1.18072316,  1.81681588,  0.85465419,  1.0933853 ])

In [11]:
np.maximum(A, B)

array([-0.58027795,  0.05304831,  1.61503833,  0.23649667,  1.65181276,
       -0.02631042,  1.52283485,  1.46179422,  1.38764981,  0.74787963])