In [1]:
import pandas as pd
from pandas import Series, DataFrame
import numpy as np

In [2]:
arr1 = np.arange(9).reshape(3, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
np.concatenate([arr1, arr1], axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [5]:
np.concatenate([arr1, arr1], axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
ser1 = Series([0,1,2], index=['T', 'U', 'V'])
ser2 = Series([3,4], index=['X', 'Y'])

In [8]:
ser1


T    0
U    1
V    2
dtype: int64

In [9]:
ser2

X    3
Y    4
dtype: int64

In [10]:
pd.concat([ser1, ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [13]:
pd.concat([ser1, ser2], axis=1)

0   1
T   0 NaN
U   1 NaN
V   2 NaN
X NaN   3
Y NaN   4

In [14]:
pd.concat([ser1, ser2], keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [26]:
dframe1 = DataFrame(np.random.rand(4,3), 
                    columns=['X', 'Y', 'Z'])

dframe2 = DataFrame(np.random.rand(3,3), 
                    columns=['Y', 'Q', 'X'])

In [17]:
dframe1

X         Y         Z
0  0.281785  0.718129  0.483203
1  0.140330  0.813662  0.609721
2  0.060529  0.971082  0.724917
3  0.548941  0.926904  0.657273

In [18]:
dframe2

Y         Q         X
0  0.858701  0.057290  0.436742
1  0.637245  0.036001  0.191145
2  0.270194  0.212318  0.975912

In [20]:
pd.concat([dframe1, dframe2])

Q         X         Y         Z
0       NaN  0.281785  0.718129  0.483203
1       NaN  0.140330  0.813662  0.609721
2       NaN  0.060529  0.971082  0.724917
3       NaN  0.548941  0.926904  0.657273
0  0.057290  0.436742  0.858701       NaN
1  0.036001  0.191145  0.637245       NaN
2  0.212318  0.975912  0.270194       NaN

In [21]:
pd.concat([dframe1, dframe2], ignore_index=True)

Q         X         Y         Z
0       NaN  0.281785  0.718129  0.483203
1       NaN  0.140330  0.813662  0.609721
2       NaN  0.060529  0.971082  0.724917
3       NaN  0.548941  0.926904  0.657273
4  0.057290  0.436742  0.858701       NaN
5  0.036001  0.191145  0.637245       NaN
6  0.212318  0.975912  0.270194       NaN

In [25]:
dframe3 = DataFrame({'key': ['X', 'Z', 'Y', 'Z', 'X', 'X'],
                     'data_set_1': np.arange(6)})

In [24]:
dframe4 = DataFrame({'key': ['Q', 'Y', 'Z'],
                     'data_set_2': [1,2,3]})

In [27]:
pd.merge(dframe1, dframe2)

Empty DataFrame
Columns: [X, Y, Z, Q]
Index: []